MERGE Opportunities_Cleaned AS target
USING (
    SELECT
        ID,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Title)), ''), 'N/A'), 'n/a') AS Title,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Url)), ''), 'N/A'), 'n/a') AS Url,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Deadline)), ''), 'N/A'), 'n/a') AS Deadline,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(AwardValue)), ''), 'N/A'), 'n/a') AS AwardValue,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(CashAward)), ''), 'N/A'), 'n/a') AS CashAward,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(ContactEmail)), ''), 'N/A'), 'n/a') AS ContactEmail,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(LogoUrl)), ''), 'N/A'), 'n/a') AS LogoUrl,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(CoverImage)), ''), 'N/A'), 'n/a') AS CoverImage,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(ShortDescription)), ''), 'N/A'), 'n/a') AS ShortDescription,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Description)), ''), 'N/A'), 'n/a') AS Description,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Eligibility)), ''), 'N/A'), 'n/a') AS Eligibility,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(ContactNames)), ''), 'N/A'), 'n/a') AS ContactNames,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(OpportunityTypeId)), ''), 'N/A'), 'n/a') AS OpportunityTypeId,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(IndustryId)), ''), 'N/A'), 'n/a') AS IndustryId,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(TargetCommunityId)), ''), 'N/A'), 'n/a') AS TargetCommunityId,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(TimeZone)), ''), 'N/A'), 'n/a') AS TimeZone,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(DirectApplyLink)), ''), 'N/A'), 'n/a') AS DirectApplyLink,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(OpportunityGap)), ''), 'N/A'), 'n/a') AS OpportunityGap,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(GlobalOpportunity)), ''), 'N/A'), 'n/a') AS GlobalOpportunity,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(GlobalLocations)), ''), 'N/A'), 'n/a') AS GlobalLocations,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(CountriesEligible)), ''), 'N/A'), 'n/a') AS CountriesEligible,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(LocationDetails)), ''), 'N/A'), 'n/a') AS LocationDetails,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(SdgAlignment)), ''), 'N/A'), 'n/a') AS SdgAlignment,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(EsoWebsite)), ''), 'N/A'), 'n/a') AS EsoWebsite,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(ServiceProviderEso)), ''), 'N/A'), 'n/a') AS ServiceProviderEso,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(ApprovalStatus)), ''), 'N/A'), 'n/a') AS ApprovalStatus,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Cost)), ''), 'N/A'), 'n/a') AS Cost,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(FinancialTerms)), ''), 'N/A'), 'n/a') AS FinancialTerms,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(AreaOfFocus)), ''), 'N/A'), 'n/a') AS AreaOfFocus,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Tags)), ''), 'N/A'), 'n/a') AS Tags,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Industry)), ''), 'N/A'), 'n/a') AS Industry,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(Slug)), ''), 'N/A'), 'n/a') AS Slug,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(AwardValueStr)), ''), 'N/A'), 'n/a') AS AwardValueStr,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(DeadlineStr)), ''), 'N/A'), 'n/a') AS DeadlineStr,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(DatePosted)), ''), 'N/A'), 'n/a') AS DatePosted,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(OpportunityType)), ''), 'N/A'), 'n/a') AS OpportunityType,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(IsFeatured)), ''), 'N/A'), 'n/a') AS IsFeatured,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(PublishOnLinkedin)), ''), 'N/A'), 'n/a') AS PublishOnLinkedin,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(TargetCommunity)), ''), 'N/A'), 'n/a') AS TargetCommunity,
        NULLIF(NULLIF(NULLIF(LTRIM(RTRIM(CreatedAt)), ''), 'N/A'), 'n/a') AS CreatedAt
    FROM Opportunities
) AS source
ON target.ID = source.ID

WHEN MATCHED THEN
    UPDATE SET
        Title = source.Title,
        Url = source.Url,
        Deadline = source.Deadline,
        AwardValue = source.AwardValue,
        CashAward = source.CashAward,
        ContactEmail = source.ContactEmail,
        LogoUrl = source.LogoUrl,
        CoverImage = source.CoverImage,
        ShortDescription = source.ShortDescription,
        Description = source.Description,
        Eligibility = source.Eligibility,
        ContactNames = source.ContactNames,
        OpportunityTypeId = source.OpportunityTypeId,
        IndustryId = source.IndustryId,
        TargetCommunityId = source.TargetCommunityId,
        TimeZone = source.TimeZone,
        DirectApplyLink = source.DirectApplyLink,
        OpportunityGap = source.OpportunityGap,
        GlobalOpportunity = source.GlobalOpportunity,
        GlobalLocations = source.GlobalLocations,
        CountriesEligible = source.CountriesEligible,
        LocationDetails = source.LocationDetails,
        SdgAlignment = source.SdgAlignment,
        EsoWebsite = source.EsoWebsite,
        ServiceProviderEso = source.ServiceProviderEso,
        ApprovalStatus = source.ApprovalStatus,
        Cost = source.Cost,
        FinancialTerms = source.FinancialTerms,
        AreaOfFocus = source.AreaOfFocus,
        Tags = source.Tags,
        Industry = source.Industry,
        Slug = source.Slug,
        AwardValueStr = source.AwardValueStr,
        DeadlineStr = source.DeadlineStr,
        DatePosted = source.DatePosted,
        OpportunityType = source.OpportunityType,
        IsFeatured = source.IsFeatured,
        PublishOnLinkedin = source.PublishOnLinkedin,
        TargetCommunity = source.TargetCommunity,
        CreatedAt = source.CreatedAt

WHEN NOT MATCHED THEN
    INSERT (
        ID, Title, Url, Deadline, AwardValue, CashAward, ContactEmail, LogoUrl, CoverImage,
        ShortDescription, Description, Eligibility, ContactNames, OpportunityTypeId, IndustryId,
        TargetCommunityId, TimeZone, DirectApplyLink, OpportunityGap, GlobalOpportunity,
        GlobalLocations, CountriesEligible, LocationDetails, SdgAlignment, EsoWebsite,
        ServiceProviderEso, ApprovalStatus, Cost, FinancialTerms, AreaOfFocus, Tags, Industry,
        Slug, AwardValueStr, DeadlineStr, DatePosted, OpportunityType, IsFeatured,
        PublishOnLinkedin, TargetCommunity, CreatedAt
    )
    VALUES (
        source.ID, source.Title, source.Url, source.Deadline, source.AwardValue, source.CashAward,
        source.ContactEmail, source.LogoUrl, source.CoverImage, source.ShortDescription,
        source.Description, source.Eligibility, source.ContactNames, source.OpportunityTypeId,
        source.IndustryId, source.TargetCommunityId, source.TimeZone, source.DirectApplyLink,
        source.OpportunityGap, source.GlobalOpportunity, source.GlobalLocations,
        source.CountriesEligible, source.LocationDetails, source.SdgAlignment, source.EsoWebsite,
        source.ServiceProviderEso, source.ApprovalStatus, source.Cost, source.FinancialTerms,
        source.AreaOfFocus, source.Tags, source.Industry, source.Slug, source.AwardValueStr,
        source.DeadlineStr, source.DatePosted, source.OpportunityType, source.IsFeatured,
        source.PublishOnLinkedin, source.TargetCommunity, source.CreatedAt
    );

